extern unsigned char assets_img_black_bmp_gz[];
extern unsigned char assets_img_cleared_bmp_gz[];
extern unsigned char assets_img_congrats_bmp_gz[];
extern unsigned char assets_img_copiedtoclipboard_bmp_gz[];
extern unsigned char assets_img_help_bmp_gz[];
extern unsigned char assets_img_loaded_bmp_gz[];
extern unsigned char assets_img_nosave_bmp_gz[];
extern unsigned char assets_img_nosol_bmp_gz[];
extern unsigned char assets_img_playfromclipboard_bmp_gz[];
extern unsigned char assets_img_saved_bmp_gz[];
extern unsigned char assets_img_snapshottoclipboard_bmp_gz[];
extern unsigned char assets_img_solved_bmp_gz[];
extern unsigned char skins_yoshi_bmp_gz[];
extern unsigned char assets_levels_microban_xsb_gz[];
extern unsigned char assets_levels_sasquatch3_xsb_gz[];
extern unsigned char assets_levels_sasquatch_xsb_gz[];
extern unsigned char assets_font_0_bmp_gz[];
extern unsigned char assets_font_1_bmp_gz[];
extern unsigned char assets_font_2_bmp_gz[];
extern unsigned char assets_font_3_bmp_gz[];
extern unsigned char assets_font_4_bmp_gz[];
extern unsigned char assets_font_5_bmp_gz[];
extern unsigned char assets_font_6_bmp_gz[];
extern unsigned char assets_font_7_bmp_gz[];
extern unsigned char assets_font_8_bmp_gz[];
extern unsigned char assets_font_9_bmp_gz[];
extern unsigned char assets_font_aa_bmp_gz[];
extern unsigned char assets_font_a_bmp_gz[];
extern unsigned char assets_font_bb_bmp_gz[];
extern unsigned char assets_font_b_bmp_gz[];
extern unsigned char assets_font_c_bmp_gz[];
extern unsigned char assets_font_cc_bmp_gz[];
extern unsigned char assets_font_d_bmp_gz[];
extern unsigned char assets_font_dd_bmp_gz[];
extern unsigned char assets_font_e_bmp_gz[];
extern unsigned char assets_font_ee_bmp_gz[];
extern unsigned char assets_font_f_bmp_gz[];
extern unsigned char assets_font_ff_bmp_gz[];
extern unsigned char assets_font_g_bmp_gz[];
extern unsigned char assets_font_gg_bmp_gz[];
extern unsigned char assets_font_h_bmp_gz[];
extern unsigned char assets_font_hh_bmp_gz[];
extern unsigned char assets_font_i_bmp_gz[];
extern unsigned char assets_font_ii_bmp_gz[];
extern unsigned char assets_font_j_bmp_gz[];
extern unsigned char assets_font_jj_bmp_gz[];
extern unsigned char assets_font_k_bmp_gz[];
extern unsigned char assets_font_kk_bmp_gz[];
extern unsigned char assets_font_l_bmp_gz[];
extern unsigned char assets_font_ll_bmp_gz[];
extern unsigned char assets_font_m_bmp_gz[];
extern unsigned char assets_font_mm_bmp_gz[];
extern unsigned char assets_font_n_bmp_gz[];
extern unsigned char assets_font_nn_bmp_gz[];
extern unsigned char assets_font_o_bmp_gz[];
extern unsigned char assets_font_oo_bmp_gz[];
extern unsigned char assets_font_p_bmp_gz[];
extern unsigned char assets_font_pp_bmp_gz[];
extern unsigned char assets_font_q_bmp_gz[];
extern unsigned char assets_font_qq_bmp_gz[];
extern unsigned char assets_font_r_bmp_gz[];
extern unsigned char assets_font_rr_bmp_gz[];
extern unsigned char assets_font_s_bmp_gz[];
extern unsigned char assets_font_ss_bmp_gz[];
extern unsigned char assets_font_sym_ampe_bmp_gz[];
extern unsigned char assets_font_sym_apos_bmp_gz[];
extern unsigned char assets_font_sym_at_bmp_gz[];
extern unsigned char assets_font_sym_back_bmp_gz[];
extern unsigned char assets_font_sym_bksl_bmp_gz[];
extern unsigned char assets_font_sym_bra1_bmp_gz[];
extern unsigned char assets_font_sym_bra2_bmp_gz[];
extern unsigned char assets_font_sym_care_bmp_gz[];
extern unsigned char assets_font_sym_col_bmp_gz[];
extern unsigned char assets_font_sym_comm_bmp_gz[];
extern unsigned char assets_font_sym_curl1_bmp_gz[];
extern unsigned char assets_font_sym_curl2_bmp_gz[];
extern unsigned char assets_font_sym_doll_bmp_gz[];
extern unsigned char assets_font_sym_dot_bmp_gz[];
extern unsigned char assets_font_sym_equa_bmp_gz[];
extern unsigned char assets_font_sym_excl_bmp_gz[];
extern unsigned char assets_font_sym_gt_bmp_gz[];
extern unsigned char assets_font_sym_hash_bmp_gz[];
extern unsigned char assets_font_sym_inter_bmp_gz[];
extern unsigned char assets_font_sym_lt_bmp_gz[];
extern unsigned char assets_font_sym_minu_bmp_gz[];
extern unsigned char assets_font_sym_par1_bmp_gz[];
extern unsigned char assets_font_sym_par2_bmp_gz[];
extern unsigned char assets_font_sym_perc_bmp_gz[];
extern unsigned char assets_font_sym_pipe_bmp_gz[];
extern unsigned char assets_font_sym_plus_bmp_gz[];
extern unsigned char assets_font_sym_quot_bmp_gz[];
extern unsigned char assets_font_sym_scol_bmp_gz[];
extern unsigned char assets_font_sym_slas_bmp_gz[];
extern unsigned char assets_font_sym_star_bmp_gz[];
extern unsigned char assets_font_sym_tild_bmp_gz[];
extern unsigned char assets_font_sym_unde_bmp_gz[];
extern unsigned char assets_font_t_bmp_gz[];
extern unsigned char assets_font_tt_bmp_gz[];
extern unsigned char assets_font_u_bmp_gz[];
extern unsigned char assets_font_uu_bmp_gz[];
extern unsigned char assets_font_v_bmp_gz[];
extern unsigned char assets_font_vv_bmp_gz[];
extern unsigned char assets_font_w_bmp_gz[];
extern unsigned char assets_font_ww_bmp_gz[];
extern unsigned char assets_font_x_bmp_gz[];
extern unsigned char assets_font_xx_bmp_gz[];
extern unsigned char assets_font_y_bmp_gz[];
extern unsigned char assets_font_yy_bmp_gz[];
extern unsigned char assets_font_z_bmp_gz[];
extern unsigned char assets_font_zz_bmp_gz[];
extern unsigned char assets_icon_bmp_gz[];
extern size_t assets_img_black_bmp_gz_len;
extern size_t assets_img_cleared_bmp_gz_len;
extern size_t assets_img_congrats_bmp_gz_len;
extern size_t assets_img_copiedtoclipboard_bmp_gz_len;
extern size_t assets_img_help_bmp_gz_len;
extern size_t assets_img_loaded_bmp_gz_len;
extern size_t assets_img_nosave_bmp_gz_len;
extern size_t assets_img_nosol_bmp_gz_len;
extern size_t assets_img_playfromclipboard_bmp_gz_len;
extern size_t assets_img_saved_bmp_gz_len;
extern size_t assets_img_snapshottoclipboard_bmp_gz_len;
extern size_t assets_img_solved_bmp_gz_len;
extern size_t skins_yoshi_bmp_gz_len;
extern size_t assets_levels_microban_xsb_gz_len;
extern size_t assets_levels_sasquatch3_xsb_gz_len;
extern size_t assets_levels_sasquatch_xsb_gz_len;
extern size_t assets_font_0_bmp_gz_len;
extern size_t assets_font_1_bmp_gz_len;
extern size_t assets_font_2_bmp_gz_len;
extern size_t assets_font_3_bmp_gz_len;
extern size_t assets_font_4_bmp_gz_len;
extern size_t assets_font_5_bmp_gz_len;
extern size_t assets_font_6_bmp_gz_len;
extern size_t assets_font_7_bmp_gz_len;
extern size_t assets_font_8_bmp_gz_len;
extern size_t assets_font_9_bmp_gz_len;
extern size_t assets_font_aa_bmp_gz_len;
extern size_t assets_font_a_bmp_gz_len;
extern size_t assets_font_bb_bmp_gz_len;
extern size_t assets_font_b_bmp_gz_len;
extern size_t assets_font_c_bmp_gz_len;
extern size_t assets_font_cc_bmp_gz_len;
extern size_t assets_font_d_bmp_gz_len;
extern size_t assets_font_dd_bmp_gz_len;
extern size_t assets_font_e_bmp_gz_len;
extern size_t assets_font_ee_bmp_gz_len;
extern size_t assets_font_f_bmp_gz_len;
extern size_t assets_font_ff_bmp_gz_len;
extern size_t assets_font_g_bmp_gz_len;
extern size_t assets_font_gg_bmp_gz_len;
extern size_t assets_font_h_bmp_gz_len;
extern size_t assets_font_hh_bmp_gz_len;
extern size_t assets_font_i_bmp_gz_len;
extern size_t assets_font_ii_bmp_gz_len;
extern size_t assets_font_j_bmp_gz_len;
extern size_t assets_font_jj_bmp_gz_len;
extern size_t assets_font_k_bmp_gz_len;
extern size_t assets_font_kk_bmp_gz_len;
extern size_t assets_font_l_bmp_gz_len;
extern size_t assets_font_ll_bmp_gz_len;
extern size_t assets_font_m_bmp_gz_len;
extern size_t assets_font_mm_bmp_gz_len;
extern size_t assets_font_n_bmp_gz_len;
extern size_t assets_font_nn_bmp_gz_len;
extern size_t assets_font_o_bmp_gz_len;
extern size_t assets_font_oo_bmp_gz_len;
extern size_t assets_font_p_bmp_gz_len;
extern size_t assets_font_pp_bmp_gz_len;
extern size_t assets_font_q_bmp_gz_len;
extern size_t assets_font_qq_bmp_gz_len;
extern size_t assets_font_r_bmp_gz_len;
extern size_t assets_font_rr_bmp_gz_len;
extern size_t assets_font_s_bmp_gz_len;
extern size_t assets_font_ss_bmp_gz_len;
extern size_t assets_font_sym_ampe_bmp_gz_len;
extern size_t assets_font_sym_apos_bmp_gz_len;
extern size_t assets_font_sym_at_bmp_gz_len;
extern size_t assets_font_sym_back_bmp_gz_len;
extern size_t assets_font_sym_bksl_bmp_gz_len;
extern size_t assets_font_sym_bra1_bmp_gz_len;
extern size_t assets_font_sym_bra2_bmp_gz_len;
extern size_t assets_font_sym_care_bmp_gz_len;
extern size_t assets_font_sym_col_bmp_gz_len;
extern size_t assets_font_sym_comm_bmp_gz_len;
extern size_t assets_font_sym_curl1_bmp_gz_len;
extern size_t assets_font_sym_curl2_bmp_gz_len;
extern size_t assets_font_sym_doll_bmp_gz_len;
extern size_t assets_font_sym_dot_bmp_gz_len;
extern size_t assets_font_sym_equa_bmp_gz_len;
extern size_t assets_font_sym_excl_bmp_gz_len;
extern size_t assets_font_sym_gt_bmp_gz_len;
extern size_t assets_font_sym_hash_bmp_gz_len;
extern size_t assets_font_sym_inter_bmp_gz_len;
extern size_t assets_font_sym_lt_bmp_gz_len;
extern size_t assets_font_sym_minu_bmp_gz_len;
extern size_t assets_font_sym_par1_bmp_gz_len;
extern size_t assets_font_sym_par2_bmp_gz_len;
extern size_t assets_font_sym_perc_bmp_gz_len;
extern size_t assets_font_sym_pipe_bmp_gz_len;
extern size_t assets_font_sym_plus_bmp_gz_len;
extern size_t assets_font_sym_quot_bmp_gz_len;
extern size_t assets_font_sym_scol_bmp_gz_len;
extern size_t assets_font_sym_slas_bmp_gz_len;
extern size_t assets_font_sym_star_bmp_gz_len;
extern size_t assets_font_sym_tild_bmp_gz_len;
extern size_t assets_font_sym_unde_bmp_gz_len;
extern size_t assets_font_t_bmp_gz_len;
extern size_t assets_font_tt_bmp_gz_len;
extern size_t assets_font_u_bmp_gz_len;
extern size_t assets_font_uu_bmp_gz_len;
extern size_t assets_font_v_bmp_gz_len;
extern size_t assets_font_vv_bmp_gz_len;
extern size_t assets_font_w_bmp_gz_len;
extern size_t assets_font_ww_bmp_gz_len;
extern size_t assets_font_x_bmp_gz_len;
extern size_t assets_font_xx_bmp_gz_len;
extern size_t assets_font_y_bmp_gz_len;
extern size_t assets_font_yy_bmp_gz_len;
extern size_t assets_font_z_bmp_gz_len;
extern size_t assets_font_zz_bmp_gz_len;
extern size_t assets_icon_bmp_gz_len;
